/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    Calculate calculate = new Calculate();
    int x = 2;
    int y = 3;
    System.out.println(new App().getGreeting());
    System.out.println("Sum of" + x + " and " + y + " is " + calculate.sum(x, y) + ". " + "Average is "
        + calculate.average((double) x, (double) y) + ".");

    System.out.println("Sum of 1 to 10 is " + calculate.sum1to10() + ". Average is " + calculate.ave1to10() + ".");

    System.out.println("Sum of odd 1 to 10 is " + calculate.oddsum() + ". Sum of even is " + calculate.evensum() + ".");
  }
}
