/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void testAppReternHelloWorld() {
    App classUnderTest = new App();
    assertEquals("Hello World!", classUnderTest.getGreeting());
  }

  @Test
  public void testSum() {
    Calculate calculate = new Calculate();
    int expected = 5;
    assertEquals(expected, calculate.sum(2, 3));
  }

  @Test
  public void testave() {
    Calculate calculate = new Calculate();
    double expected = 2.5;
    assertEquals(expected, calculate.average(2.0, 3.0), 0);
  }

  @Test
  public void test1to10() {
    Calculate calculate = new Calculate();
    int expected = 55;
    assertEquals(expected, calculate.sum1to10());
  }

  @Test
  public void testave1to10() {
    Calculate calculate = new Calculate();
    double expected = 5.5;
    assertEquals(expected, calculate.ave1to10(), 0);
  }

  @Test
  public void testodd() {
    Calculate calculate = new Calculate();
    int expected = 25;
    assertEquals(expected, calculate.oddsum());
  }

  @Test
  public void testeven() {
    Calculate calculate = new Calculate();
    int expected = 30;
    assertEquals(expected, calculate.evensum());
  }
}
